### ISSUE TITLE
Resource types

### ISSUE THREAD

**Issue by evincarofautumn** [evincarofautumn/kitten#119]
For tracking and enforcing the semantics of resources:
- Whether a resource is copyable
- Whether it must be consumed
- Whether it must be disposed before another resource
- Whether to dispose it or leak it to a caller (say)

**Comment by gilbert** [comment]
What are your thoughts on this? I'm working on a concatenative language and am considering tracking similar properties.

**Comment by evincarofautumn** [comment]
I’m going to have some smart pointer types (`Owned<T>`, `Shared<T>`) and enforce usage by restricting copies and drops using traits. #156 has some thoughts on that. I closed this because it’s old and I’m going to add that stuff when I do the ctor/dtor implementation anyway. Feel free to ask any other questions on that issue.
