### ISSUE TITLE
Embedded Systems

### ISSUE THREAD

**Issue by trans** [evincarofautumn/kitten#161]
I know Kitten is more-or-less "Haskell on a Stack Machine". I think that is awesome. But will there be facilities for doing embedded systems development? If you want to attract Forthers and not just Haskellers, that's something you probably want to consider.

**Comment by evincarofautumn** [comment]
Depends on what you mean by “embedded”—I’ve been thinking about some lower-level stuff lately, for example [Arithmetic Types in Kitten](http://evincarofautumn.blogspot.com/2016/09/arithmetic-types-in-kitten.html). I’d like to at least avoid libc, and ideally be able to produce freestanding executables. But I don’t know what it would take to make Kitten suitable for the kinds of things people do in Forth.
