### ISSUE TITLE
Why does kitten have variables?

### ISSUE THREAD

**Issue by Josef-Vonasek** [evincarofautumn/kitten#194]
Concatenative languages like Joy do not have lambdas. Why does kitten have them?

* It makes parsing more complicated.
* It requires abstraction algorithm or graph reduction.

Are lambdas more powerful than `quote` and `eval` (`[ .. ] i`)?

**Comment by suhr** [comment]
> `-> x y z { x + y + z }` is exactly equivalent to `{ -> x y z; x + y + z }`

Looks like it's just a yet another syntax sugar.

**Comment by Josef-Vonasek** [comment]
What do you mean it is just a syntax sugar. `{ -> a; a }` **is** lambda and you need abstraction algorithm to convert it to series of combinators.

**Comment by suhr** [comment]
So your question is “Why does Kitten support variables?”. Well, they are sometimes really convenient.

**Comment by Josef-Vonasek** [comment]
But aren't they also really inefficient? To my understanding the most efficient abstraction algorithm produces O(LOC^2). Going from 200e+3 to 40e+9 lines of code is pretty crazy.

**Comment by evincarofautumn** [comment]
Because they’re convenient and can help avoid writing brittle code in some cases.

I don’t use an abstraction algorithm, I just handle them like almost every other compiler—they’ll end up in registers or on the call stack.

**Comment by Josef-Vonasek** [comment]
So in other words `-> a b; swap ...   ==   -> b a; ...`?

**Comment by evincarofautumn** [comment]
If I understand your question, yes: `swap -> a, b; …` = `-> b, a; …`. The latest compiler doesn’t have a finished code generator yet, but `swap` will be inlined, giving `-> x, y; y x -> a, b; …` and then the redundant loads & stores will be simplified to `-> b, a; …` (or even further, depending on `…`). Those locals may be stored in registers if the types are small enough and there are registers available, or else spilled to the call stack, just as in a compiler for a C-like language.
