### ISSUE TITLE
Suggestion: Add some easy chat alternative like ie gitter or similar

### ISSUE THREAD

**Issue by NOP0** [evincarofautumn/kitten#199]
Tried concatenative channel on irc, but seems dead. Just a friendly suggestion for some easy place to ask questions and so on about kitten.

**Comment by evincarofautumn** [comment]
#concatenative isn’t dead, just low-traffic, and I’m not always on. I’m willing to try Gitter for Kitten-specific discussion, though, so I created https://gitter.im/kittenlang.

**Comment by brendanzab** [comment]
Might want to chuck a badge on the readme. Can't remember where to find them. You can also set up an integration that tracks issues, pull requests, and CI status, etc.

**Comment by evincarofautumn** [comment]
Added a badge to the README and set up integrations with GitHub and GitBook. I think we’re all set. :)
