### ISSUE TITLE
Is this project still being actively developed?

### ISSUE THREAD

**Issue by Kwarrtz** [evincarofautumn/kitten#214]
This repo doesn't seem to have had any activity in the last several months. If it's no longer being worked on could you update the README and website to make this clear?

**Comment by evincarofautumn** [comment]
I know it seems dead, but I am still working on it. I just haven’t been making any progress on the implementation for a while (for various reasons) so I haven’t put anything new online recently. I will however update the docs to reflect what I have been working on.

**Comment by Kwarrtz** [comment]
Glad to hear it's still alive! I'll look forward to seeing the updated docs. :)

**Comment by udexon** [comment]
Just to share with you my project: Stack Machine Metaprogramming -- a "bigger picture", everything to do with stack machine, implemented in PHP, JavaScript, Python, C/C++ so far ... and more to come.

https://github.com/udexon/SMMP
