### ISSUE TITLE
State of the compiler

### ISSUE THREAD

**Issue by bhelx** [evincarofautumn/kitten#215]
What is the state of the native code compiler? I see it's currently called out as `incomplete` in the README. I tried guessing the command to compile and tried the fibonacci example. This doesn't output anything:

```
kitten -c ir -o fib fib.ktn
```

**Comment by evincarofautumn** [comment]
There’s nothing usable right now. Originally `-cc` would use the old C backend, but that’s been broken for a while.

I’m going to have a few evenings to focus on it this week, so I’ll try to integrate what I’ve been working on behind the scenes. In the meantime you can use the interpreter.

**Comment by bhelx** [comment]
Thanks @evincarofautumn. I'll close now as this was just a question.
